# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70556a801d52a909ae463f97a9faee3758c298fa22ceaf4f0a255ac668675247cc08403f75b419f89fc54b43d1a2127a378717fd76122c2e8d870c15de80c934

test:
  secret_key_base: 9a63400f425d0d7c4fcaf0514a53efe33173392583155beb4b90dc425d5c253ef02de0a680340a73023a9874f604d607c3adc4c3b98b8082fd3438636ad86710

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
